version: '3.8'

services:
  # Packages

  redis:
    container_name: redis
    image: redis:alpine
    restart: always
    ports:
      - 6379:6379
    networks:
      - ai-colleague
    volumes:
      - redis:/data

  chromadb:
    container_name: chromadb
    image: chromadb/chroma
    environment:
      - IS_PERSISTENT=TRUE
    networks:
      - ai-colleague
    ports:
      - 8000:8000
    volumes:
      - chroma-data:/chroma/chroma

  postgres:
    image: postgis/postgis:14-3.3-alpine
    restart: always
    environment:
      - DATABASE=nvaa_ai_colleague
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    networks:
      - ai-colleague
    volumes:
      - postgres:/var/lib/postgresql/data

networks:
  ai-colleague:
    driver: bridge

volumes:
  redis:
  chroma-data:
  postgres:
