version: '3.8'

services:
  # Packages

  redis:
    container_name: redis
    image: redis:alpine
    restart: always
    ports:
      - 6379:6379
    networks:
      - ai-colleague
    volumes:
      - redis:/data

  chromadb:
    container_name: chromadb
    image: chromadb/chroma
    environment:
      - IS_PERSISTENT=TRUE
    networks:
      - ai-colleague
    ports:
      - 8000:8000
    volumes:
      - chroma-data:/chroma/chroma

networks:
  ai-colleague:
    driver: bridge

volumes:
  redis:
  chroma-data:
