apiVersion: apps/v1
kind: Deployment
metadata:
  name: ai-colleague
  namespace: ai-colleague
spec:
  replicas: 3
  selector:
    matchLabels:
      app: ai-colleague
  template:
    metadata:
      labels:
        app: ai-colleague
    spec:
      containers:
        - image: ghcr.io/nvaa-se/ai-colleague:main # {"$imagepolicy": "flux-system:cloaca"}
          resources: {}
          name: ai-colleague
          ports:
            - containerPort: 3000
          env:
            - name: DISCORD_APPLICATION_ID
              valueFrom:
                secretKeyRef:
                  name: env
                  key: DISCORD_APPLICATION_ID
            - name: DISCORD_SERVER_ID
              valueFrom:
                secretKeyRef:
                  name: env
                  key: DISCORD_SERVER_ID
            - name: DISCORD_TOKEN
              valueFrom:
                secretKeyRef:
                  name: env
                  key: DISCORD_TOKEN
            - name: MISTRAL_API_KEY
              valueFrom:
                secretKeyRef:
                  name: env
                  key: MISTRAL_API_KEY
            - name: CHROMA_HOST
              value: http://chromadb:8000
            - name: REDIS_HOST
              value: redis-master
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: redis
                  key: redis-password
          imagePullPolicy: Always
