apiVersion: apps/v1
kind: Deployment
metadata:
  name: ai-colleague
  namespace: ai-colleague
spec:
  replicas: 3
  selector:
    matchLabels:
      app: ai-colleague
  template:
    metadata:
      labels:
        app: ai-colleague
    spec:
      containers:
        - image: ghcr.io/nvaa-se/ai-colleague:main # {"$imagepolicy": "flux-system:cloaca"}
          resources: {}
          name: ai-colleague
          ports:
            - containerPort: 3000
          env:
            - name: DISCORD_APPLICATION_ID
              valueFrom:
                secretKeyRef:
                  name: env
                  key: DISCORD_APPLICATION_ID
            - name: DISCORD_SERVER_ID
              valueFrom:
                secretKeyRef:
                  name: env
                  key: DISCORD_SERVER_ID
            - name: DISCORD_TOKEN
              valueFrom:
                secretKeyRef:
                  name: env
                  key: DISCORD_TOKEN
            - name: GOTENBERG_URL
              value: http://gotenberg:3000
            - name: OPENAI_API_KEY
              valueFrom:
                secretKeyRef:
                  name: env
                  key: OPENAI_API_KEY
            - name: OPENAI_ORG_ID
              valueFrom:
                secretKeyRef:
                  name: env
                  key: OPENAI_ORG_ID
            - name: ELASTIC_NODE_URL
              value: http://elasticsearch:9200
            - name: ELASTIC_INDEX_NAME
              value: reports
            # - name: CHROMA_TOKEN
            #   valueFrom:
            #     secretKeyRef:
            #       name: chromadb-auth
            #       key: token
            - name: CHROMA_HOST
              value: http://chromadb:8000
            - name: REDIS_HOST
              value: redis-master
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: redis
                  key: redis-password
          imagePullPolicy: Always
